// ============================================================
// NVIDIA NIM Model Catalog — Complete Reference
// ============================================================
// All models available via the NVIDIA NIM API (free tier).
// Organized by category: chat, reasoning, vision, code, embedding, fast.
// ============================================================

import type { NvidiaModel, ModelCategory } from "@/lib/types";

// ────────────────────────────────────────────────────────────
// Helper: extract provider from model ID
// ────────────────────────────────────────────────────────────
function p(id: string): string {
  return id.split("/")[0] ?? "unknown";
}

// ============================================================
// §1  CHAT Models (general-purpose instruction following)
// ============================================================

const CHAT_MODELS: NvidiaModel[] = [
  {
    id: "01-ai/yi-large",
    name: "Yi Large",
    provider: p("01-ai/yi-large"),
    contextLength: 32768,
    supportsStreaming: true,
    supportsVision: false,
    isFree: true,
    category: "chat" as ModelCategory,
  },
  {
    id: "abacusai/dracarys-llama-3.1-70b-instruct",
    name: "Dracarys Llama 3.1 70B Instruct",
    provider: p("abacusai/dracarys-llama-3.1-70b-instruct"),
    contextLength: 131072,
    supportsStreaming: true,
    supportsVision: false,
    isFree: true,
    category: "chat" as ModelCategory,
  },
  {
    id: "ai21labs/jamba-1.5-large-instruct",
    name: "Jamba 1.5 Large Instruct",
    provider: p("ai21labs/jamba-1.5-large-instruct"),
    contextLength: 262144,
    supportsStreaming: true,
    supportsVision: false,
    isFree: true,
    category: "chat" as ModelCategory,
  },
  {
    id: "ai21labs/jamba-1.5-mini-instruct",
    name: "Jamba 1.5 Mini Instruct",
    provider: p("ai21labs/jamba-1.5-mini-instruct"),
    contextLength: 262144,
    supportsStreaming: true,
    supportsVision: false,
    isFree: true,
    category: "chat" as ModelCategory,
  },
  {
    id: "aisingapore/sea-lion-7b-instruct",
    name: "SEA-LION 7B Instruct",
    provider: p("aisingapore/sea-lion-7b-instruct"),
    contextLength: 32768,
    supportsStreaming: true,
    supportsVision: false,
    isFree: true,
    category: "chat" as ModelCategory,
  },
  {
    id: "baichuan-inc/baichuan2-13b-chat",
    name: "Baichuan2 13B Chat",
    provider: p("baichuan-inc/baichuan2-13b-chat"),
    contextLength: 32768,
    supportsStreaming: true,
    supportsVision: false,
    isFree: true,
    category: "chat" as ModelCategory,
  },
  {
    id: "bytedance/seed-oss-36b-instruct",
    name: "Seed OSS 36B Instruct",
    provider: p("bytedance/seed-oss-36b-instruct"),
    contextLength: 131072,
    supportsStreaming: true,
    supportsVision: false,
    isFree: true,
    category: "chat" as ModelCategory,
  },
  {
    id: "databricks/dbrx-instruct",
    name: "DBRX Instruct",
    provider: p("databricks/dbrx-instruct"),
    contextLength: 32768,
    supportsStreaming: true,
    supportsVision: false,
    isFree: true,
    category: "chat" as ModelCategory,
  },
  {
    id: "deepseek-ai/deepseek-v3.1",
    name: "DeepSeek V3.1",
    provider: p("deepseek-ai/deepseek-v3.1"),
    contextLength: 131072,
    supportsStreaming: true,
    supportsVision: false,
    isFree: true,
    category: "chat" as ModelCategory,
  },
  {
    id: "deepseek-ai/deepseek-v3.1-terminus",
    name: "DeepSeek V3.1 Terminus",
    provider: p("deepseek-ai/deepseek-v3.1-terminus"),
    contextLength: 131072,
    supportsStreaming: true,
    supportsVision: false,
    isFree: true,
    category: "chat" as ModelCategory,
  },
  {
    id: "deepseek-ai/deepseek-v3.2",
    name: "DeepSeek V3.2",
    provider: p("deepseek-ai/deepseek-v3.2"),
    contextLength: 131072,
    supportsStreaming: true,
    supportsVision: false,
    isFree: true,
    category: "chat" as ModelCategory,
  },
  {
    id: "google/gemma-2-27b-it",
    name: "Gemma 2 27B IT",
    provider: p("google/gemma-2-27b-it"),
    contextLength: 8192,
    supportsStreaming: true,
    supportsVision: false,
    isFree: true,
    category: "chat" as ModelCategory,
  },
  {
    id: "google/gemma-2-2b-it",
    name: "Gemma 2 2B IT",
    provider: p("google/gemma-2-2b-it"),
    contextLength: 8192,
    supportsStreaming: true,
    supportsVision: false,
    isFree: true,
    category: "chat" as ModelCategory,
  },
  {
    id: "google/gemma-2-9b-it",
    name: "Gemma 2 9B IT",
    provider: p("google/gemma-2-9b-it"),
    contextLength: 8192,
    supportsStreaming: true,
    supportsVision: false,
    isFree: true,
    category: "chat" as ModelCategory,
  },
  {
    id: "google/gemma-3-12b-it",
    name: "Gemma 3 12B IT",
    provider: p("google/gemma-3-12b-it"),
    contextLength: 131072,
    supportsStreaming: true,
    supportsVision: false,
    isFree: true,
    category: "chat" as ModelCategory,
  },
  {
    id: "google/gemma-3-27b-it",
    name: "Gemma 3 27B IT",
    provider: p("google/gemma-3-27b-it"),
    contextLength: 131072,
    supportsStreaming: true,
    supportsVision: false,
    isFree: true,
    category: "chat" as ModelCategory,
  },
  {
    id: "google/gemma-3n-e2b-it",
    name: "Gemma 3n E2B IT",
    provider: p("google/gemma-3n-e2b-it"),
    contextLength: 131072,
    supportsStreaming: true,
    supportsVision: false,
    isFree: true,
    category: "chat" as ModelCategory,
  },
  {
    id: "google/gemma-3n-e4b-it",
    name: "Gemma 3n E4B IT",
    provider: p("google/gemma-3n-e4b-it"),
    contextLength: 131072,
    supportsStreaming: true,
    supportsVision: false,
    isFree: true,
    category: "chat" as ModelCategory,
  },
  {
    id: "google/gemma-7b",
    name: "Gemma 7B",
    provider: p("google/gemma-7b"),
    contextLength: 8192,
    supportsStreaming: true,
    supportsVision: false,
    isFree: true,
    category: "chat" as ModelCategory,
  },
  {
    id: "gotocompany/gemma-2-9b-cpt-sahabatai-instruct",
    name: "Gemma 2 9B CPT Sahabatai Instruct",
    provider: p("gotocompany/gemma-2-9b-cpt-sahabatai-instruct"),
    contextLength: 8192,
    supportsStreaming: true,
    supportsVision: false,
    isFree: true,
    category: "chat" as ModelCategory,
  },
  {
    id: "ibm/granite-3.0-3b-a800m-instruct",
    name: "Granite 3.0 3B A800M Instruct",
    provider: p("ibm/granite-3.0-3b-a800m-instruct"),
    contextLength: 131072,
    supportsStreaming: true,
    supportsVision: false,
    isFree: true,
    category: "chat" as ModelCategory,
  },
  {
    id: "ibm/granite-3.0-8b-instruct",
    name: "Granite 3.0 8B Instruct",
    provider: p("ibm/granite-3.0-8b-instruct"),
    contextLength: 131072,
    supportsStreaming: true,
    supportsVision: false,
    isFree: true,
    category: "chat" as ModelCategory,
  },
  {
    id: "ibm/granite-3.3-8b-instruct",
    name: "Granite 3.3 8B Instruct",
    provider: p("ibm/granite-3.3-8b-instruct"),
    contextLength: 131072,
    supportsStreaming: true,
    supportsVision: false,
    isFree: true,
    category: "chat" as ModelCategory,
  },
  {
    id: "igenius/colosseum_355b_instruct_16k",
    name: "Colosseum 355B Instruct 16K",
    provider: p("igenius/colosseum_355b_instruct_16k"),
    contextLength: 16384,
    supportsStreaming: true,
    supportsVision: false,
    isFree: true,
    category: "chat" as ModelCategory,
  },
  {
    id: "igenius/italia_10b_instruct_16k",
    name: "Italia 10B Instruct 16K",
    provider: p("igenius/italia_10b_instruct_16k"),
    contextLength: 16384,
    supportsStreaming: true,
    supportsVision: false,
    isFree: true,
    category: "chat" as ModelCategory,
  },
  {
    id: "institute-of-science-tokyo/llama-3.1-swallow-70b-instruct-v0.1",
    name: "Llama 3.1 Swallow 70B Instruct",
    provider: p("institute-of-science-tokyo/llama-3.1-swallow-70b-instruct-v0.1"),
    contextLength: 131072,
    supportsStreaming: true,
    supportsVision: false,
    isFree: true,
    category: "chat" as ModelCategory,
  },
  {
    id: "institute-of-science-tokyo/llama-3.1-swallow-8b-instruct-v0.1",
    name: "Llama 3.1 Swallow 8B Instruct",
    provider: p("institute-of-science-tokyo/llama-3.1-swallow-8b-instruct-v0.1"),
    contextLength: 131072,
    supportsStreaming: true,
    supportsVision: false,
    isFree: true,
    category: "chat" as ModelCategory,
  },
  {
    id: "marin/marin-8b-instruct",
    name: "Marin 8B Instruct",
    provider: p("marin/marin-8b-instruct"),
    contextLength: 32768,
    supportsStreaming: true,
    supportsVision: false,
    isFree: true,
    category: "chat" as ModelCategory,
  },
  {
    id: "mediatek/breeze-7b-instruct",
    name: "Breeze 7B Instruct",
    provider: p("mediatek/breeze-7b-instruct"),
    contextLength: 32768,
    supportsStreaming: true,
    supportsVision: false,
    isFree: true,
    category: "chat" as ModelCategory,
  },
  {
    id: "meta/llama-3.1-70b-instruct",
    name: "Llama 3.1 70B Instruct",
    provider: p("meta/llama-3.1-70b-instruct"),
    contextLength: 131072,
    supportsStreaming: true,
    supportsVision: false,
    isFree: true,
    category: "chat" as ModelCategory,
  },
  {
    id: "meta/llama-3.1-8b-instruct",
    name: "Llama 3.1 8B Instruct",
    provider: p("meta/llama-3.1-8b-instruct"),
    contextLength: 131072,
    supportsStreaming: true,
    supportsVision: false,
    isFree: true,
    category: "chat" as ModelCategory,
  },
  {
    id: "meta/llama-3.2-3b-instruct",
    name: "Llama 3.2 3B Instruct",
    provider: p("meta/llama-3.2-3b-instruct"),
    contextLength: 131072,
    supportsStreaming: true,
    supportsVision: false,
    isFree: true,
    category: "chat" as ModelCategory,
  },
  {
    id: "meta/llama-3.3-70b-instruct",
    name: "Llama 3.3 70B Instruct",
    provider: p("meta/llama-3.3-70b-instruct"),
    contextLength: 131072,
    supportsStreaming: true,
    supportsVision: false,
    isFree: true,
    category: "chat" as ModelCategory,
  },
  {
    id: "meta/llama-4-maverick-17b-128e-instruct",
    name: "Llama 4 Maverick 17B x128E Instruct",
    provider: p("meta/llama-4-maverick-17b-128e-instruct"),
    contextLength: 131072,
    supportsStreaming: true,
    supportsVision: false,
    isFree: true,
    category: "chat" as ModelCategory,
  },
  {
    id: "meta/llama-4-scout-17b-16e-instruct",
    name: "Llama 4 Scout 17B x16E Instruct",
    provider: p("meta/llama-4-scout-17b-16e-instruct"),
    contextLength: 131072,
    supportsStreaming: true,
    supportsVision: false,
    isFree: true,
    category: "chat" as ModelCategory,
  },
  {
    id: "meta/llama2-70b",
    name: "Llama 2 70B",
    provider: p("meta/llama2-70b"),
    contextLength: 4096,
    supportsStreaming: true,
    supportsVision: false,
    isFree: true,
    category: "chat" as ModelCategory,
  },
  {
    id: "meta/llama3-70b-instruct",
    name: "Llama 3 70B Instruct",
    provider: p("meta/llama3-70b-instruct"),
    contextLength: 8192,
    supportsStreaming: true,
    supportsVision: false,
    isFree: true,
    category: "chat" as ModelCategory,
  },
  {
    id: "meta/llama3-8b-instruct",
    name: "Llama 3 8B Instruct",
    provider: p("meta/llama3-8b-instruct"),
    contextLength: 8192,
    supportsStreaming: true,
    supportsVision: false,
    isFree: true,
    category: "chat" as ModelCategory,
  },
  {
    id: "microsoft/phi-3-medium-128k-instruct",
    name: "Phi-3 Medium 128K Instruct",
    provider: p("microsoft/phi-3-medium-128k-instruct"),
    contextLength: 128000,
    supportsStreaming: true,
    supportsVision: false,
    isFree: true,
    category: "chat" as ModelCategory,
  },
  {
    id: "microsoft/phi-3-medium-4k-instruct",
    name: "Phi-3 Medium 4K Instruct",
    provider: p("microsoft/phi-3-medium-4k-instruct"),
    contextLength: 4096,
    supportsStreaming: true,
    supportsVision: false,
    isFree: true,
    category: "chat" as ModelCategory,
  },
  {
    id: "microsoft/phi-3-mini-128k-instruct",
    name: "Phi-3 Mini 128K Instruct",
    provider: p("microsoft/phi-3-mini-128k-instruct"),
    contextLength: 128000,
    supportsStreaming: true,
    supportsVision: false,
    isFree: true,
    category: "chat" as ModelCategory,
  },
  {
    id: "microsoft/phi-3-mini-4k-instruct",
    name: "Phi-3 Mini 4K Instruct",
    provider: p("microsoft/phi-3-mini-4k-instruct"),
    contextLength: 4096,
    supportsStreaming: true,
    supportsVision: false,
    isFree: true,
    category: "chat" as ModelCategory,
  },
  {
    id: "microsoft/phi-3-small-128k-instruct",
    name: "Phi-3 Small 128K Instruct",
    provider: p("microsoft/phi-3-small-128k-instruct"),
    contextLength: 128000,
    supportsStreaming: true,
    supportsVision: false,
    isFree: true,
    category: "chat" as ModelCategory,
  },
  {
    id: "microsoft/phi-3-small-8k-instruct",
    name: "Phi-3 Small 8K Instruct",
    provider: p("microsoft/phi-3-small-8k-instruct"),
    contextLength: 8192,
    supportsStreaming: true,
    supportsVision: false,
    isFree: true,
    category: "chat" as ModelCategory,
  },
  {
    id: "microsoft/phi-3.5-mini-instruct",
    name: "Phi-3.5 Mini Instruct",
    provider: p("microsoft/phi-3.5-mini-instruct"),
    contextLength: 131072,
    supportsStreaming: true,
    supportsVision: false,
    isFree: true,
    category: "chat" as ModelCategory,
  },
  {
    id: "microsoft/phi-3.5-moe-instruct",
    name: "Phi-3.5 MoE Instruct",
    provider: p("microsoft/phi-3.5-moe-instruct"),
    contextLength: 131072,
    supportsStreaming: true,
    supportsVision: false,
    isFree: true,
    category: "chat" as ModelCategory,
  },
  {
    id: "minimaxai/minimax-m2.5",
    name: "MiniMax M2.5",
    provider: p("minimaxai/minimax-m2.5"),
    contextLength: 131072,
    supportsStreaming: true,
    supportsVision: false,
    isFree: true,
    category: "chat" as ModelCategory,
  },
  {
    id: "mistralai/magistral-small-2506",
    name: "Mistral Small 2506",
    provider: p("mistralai/magistral-small-2506"),
    contextLength: 131072,
    supportsStreaming: true,
    supportsVision: false,
    isFree: true,
    category: "chat" as ModelCategory,
  },
  {
    id: "mistralai/mathstral-7b-v0.1",
    name: "Mathstral 7B",
    provider: p("mistralai/mathstral-7b-v0.1"),
    contextLength: 32768,
    supportsStreaming: true,
    supportsVision: false,
    isFree: true,
    category: "chat" as ModelCategory,
  },
  {
    id: "mistralai/ministral-14b-instruct-2512",
    name: "Ministral 14B Instruct",
    provider: p("mistralai/ministral-14b-instruct-2512"),
    contextLength: 131072,
    supportsStreaming: true,
    supportsVision: false,
    isFree: true,
    category: "chat" as ModelCategory,
  },
  {
    id: "mistralai/mistral-7b-instruct-v0.2",
    name: "Mistral 7B Instruct v0.2",
    provider: p("mistralai/mistral-7b-instruct-v0.2"),
    contextLength: 32768,
    supportsStreaming: true,
    supportsVision: false,
    isFree: true,
    category: "chat" as ModelCategory,
  },
  {
    id: "mistralai/mistral-7b-instruct-v0.3",
    name: "Mistral 7B Instruct v0.3",
    provider: p("mistralai/mistral-7b-instruct-v0.3"),
    contextLength: 32768,
    supportsStreaming: true,
    supportsVision: false,
    isFree: true,
    category: "chat" as ModelCategory,
  },
  {
    id: "mistralai/mistral-large",
    name: "Mistral Large",
    provider: p("mistralai/mistral-large"),
    contextLength: 32768,
    supportsStreaming: true,
    supportsVision: false,
    isFree: true,
    category: "chat" as ModelCategory,
  },
  {
    id: "mistralai/mistral-large-2-instruct",
    name: "Mistral Large 2 Instruct",
    provider: p("mistralai/mistral-large-2-instruct"),
    contextLength: 131072,
    supportsStreaming: true,
    supportsVision: false,
    isFree: true,
    category: "chat" as ModelCategory,
  },
  {
    id: "mistralai/mistral-large-3-675b-instruct-2512",
    name: "Mistral Large 3 675B Instruct",
    provider: p("mistralai/mistral-large-3-675b-instruct-2512"),
    contextLength: 131072,
    supportsStreaming: true,
    supportsVision: false,
    isFree: true,
    category: "chat" as ModelCategory,
  },
  {
    id: "mistralai/mistral-medium-3-instruct",
    name: "Mistral Medium 3 Instruct",
    provider: p("mistralai/mistral-medium-3-instruct"),
    contextLength: 131072,
    supportsStreaming: true,
    supportsVision: false,
    isFree: true,
    category: "chat" as ModelCategory,
  },
  {
    id: "mistralai/mistral-nemotron",
    name: "Mistral Nemotron",
    provider: p("mistralai/mistral-nemotron"),
    contextLength: 131072,
    supportsStreaming: true,
    supportsVision: false,
    isFree: true,
    category: "chat" as ModelCategory,
  },
  {
    id: "mistralai/mistral-small-24b-instruct",
    name: "Mistral Small 24B Instruct",
    provider: p("mistralai/mistral-small-24b-instruct"),
    contextLength: 131072,
    supportsStreaming: true,
    supportsVision: false,
    isFree: true,
    category: "chat" as ModelCategory,
  },
  {
    id: "mistralai/mistral-small-3.1-24b-instruct-2503",
    name: "Mistral Small 3.1 24B Instruct",
    provider: p("mistralai/mistral-small-3.1-24b-instruct-2503"),
    contextLength: 131072,
    supportsStreaming: true,
    supportsVision: false,
    isFree: true,
    category: "chat" as ModelCategory,
  },
  {
    id: "mistralai/mixtral-8x22b-instruct-v0.1",
    name: "Mixtral 8x22B Instruct",
    provider: p("mistralai/mixtral-8x22b-instruct-v0.1"),
    contextLength: 65536,
    supportsStreaming: true,
    supportsVision: false,
    isFree: true,
    category: "chat" as ModelCategory,
  },
  {
    id: "mistralai/mixtral-8x22b-v0.1",
    name: "Mixtral 8x22B",
    provider: p("mistralai/mixtral-8x22b-v0.1"),
    contextLength: 65536,
    supportsStreaming: true,
    supportsVision: false,
    isFree: true,
    category: "chat" as ModelCategory,
  },
  {
    id: "mistralai/mixtral-8x7b-instruct-v0.1",
    name: "Mixtral 8x7B Instruct",
    provider: p("mistralai/mixtral-8x7b-instruct-v0.1"),
    contextLength: 32768,
    supportsStreaming: true,
    supportsVision: false,
    isFree: true,
    category: "chat" as ModelCategory,
  },
  {
    id: "moonshotai/kimi-k2-instruct",
    name: "Kimi K2 Instruct",
    provider: p("moonshotai/kimi-k2-instruct"),
    contextLength: 131072,
    supportsStreaming: true,
    supportsVision: false,
    isFree: true,
    category: "chat" as ModelCategory,
  },
  {
    id: "moonshotai/kimi-k2-instruct-0905",
    name: "Kimi K2 Instruct 0905",
    provider: p("moonshotai/kimi-k2-instruct-0905"),
    contextLength: 131072,
    supportsStreaming: true,
    supportsVision: false,
    isFree: true,
    category: "chat" as ModelCategory,
  },
  {
    id: "moonshotai/kimi-k2.5",
    name: "Kimi K2.5",
    provider: p("moonshotai/kimi-k2.5"),
    contextLength: 131072,
    supportsStreaming: true,
    supportsVision: false,
    isFree: true,
    category: "chat" as ModelCategory,
  },
  {
    id: "nv-mistralai/mistral-nemo-12b-instruct",
    name: "Mistral Nemo 12B Instruct",
    provider: p("nv-mistralai/mistral-nemo-12b-instruct"),
    contextLength: 131072,
    supportsStreaming: true,
    supportsVision: false,
    isFree: true,
    category: "chat" as ModelCategory,
  },
  {
    id: "nvidia/llama-3.1-nemotron-51b-instruct",
    name: "Llama 3.1 Nemotron 51B Instruct",
    provider: p("nvidia/llama-3.1-nemotron-51b-instruct"),
    contextLength: 131072,
    supportsStreaming: true,
    supportsVision: false,
    isFree: true,
    category: "chat" as ModelCategory,
  },
  {
    id: "nvidia/llama-3.1-nemotron-70b-instruct",
    name: "Llama 3.1 Nemotron 70B Instruct",
    provider: p("nvidia/llama-3.1-nemotron-70b-instruct"),
    contextLength: 131072,
    supportsStreaming: true,
    supportsVision: false,
    isFree: true,
    category: "chat" as ModelCategory,
  },
  {
    id: "nvidia/llama-3.1-nemotron-ultra-253b-v1",
    name: "Llama 3.1 Nemotron Ultra 253B",
    provider: p("nvidia/llama-3.1-nemotron-ultra-253b-v1"),
    contextLength: 131072,
    supportsStreaming: true,
    supportsVision: false,
    isFree: true,
    category: "chat" as ModelCategory,
  },
  {
    id: "nvidia/llama3-chatqa-1.5-70b",
    name: "Llama 3 ChatQA 1.5 70B",
    provider: p("nvidia/llama3-chatqa-1.5-70b"),
    contextLength: 131072,
    supportsStreaming: true,
    supportsVision: false,
    isFree: true,
    category: "chat" as ModelCategory,
  },
  {
    id: "nvidia/llama3-chatqa-1.5-8b",
    name: "Llama 3 ChatQA 1.5 8B",
    provider: p("nvidia/llama3-chatqa-1.5-8b"),
    contextLength: 8192,
    supportsStreaming: true,
    supportsVision: false,
    isFree: true,
    category: "chat" as ModelCategory,
  },
  {
    id: "nvidia/mistral-nemo-minitron-8b-8k-instruct",
    name: "Mistral Nemo Minitron 8B 8K Instruct",
    provider: p("nvidia/mistral-nemo-minitron-8b-8k-instruct"),
    contextLength: 8192,
    supportsStreaming: true,
    supportsVision: false,
    isFree: true,
    category: "chat" as ModelCategory,
  },
  {
    id: "nvidia/nemotron-4-340b-instruct",
    name: "Nemotron 4 340B Instruct",
    provider: p("nvidia/nemotron-4-340b-instruct"),
    contextLength: 4096,
    supportsStreaming: true,
    supportsVision: false,
    isFree: true,
    category: "chat" as ModelCategory,
  },
  {
    id: "nvidia/nemotron-4-mini-hindi-4b-instruct",
    name: "Nemotron 4 Mini Hindi 4B Instruct",
    provider: p("nvidia/nemotron-4-mini-hindi-4b-instruct"),
    contextLength: 4096,
    supportsStreaming: true,
    supportsVision: false,
    isFree: true,
    category: "chat" as ModelCategory,
  },
  {
    id: "nvidia/nemotron-mini-4b-instruct",
    name: "Nemotron Mini 4B Instruct",
    provider: p("nvidia/nemotron-mini-4b-instruct"),
    contextLength: 4096,
    supportsStreaming: true,
    supportsVision: false,
    isFree: true,
    category: "chat" as ModelCategory,
  },
  {
    id: "openai/gpt-oss-120b",
    name: "GPT OSS 120B",
    provider: p("openai/gpt-oss-120b"),
    contextLength: 131072,
    supportsStreaming: true,
    supportsVision: false,
    isFree: true,
    category: "chat" as ModelCategory,
  },
  {
    id: "openai/gpt-oss-20b",
    name: "GPT OSS 20B",
    provider: p("openai/gpt-oss-20b"),
    contextLength: 131072,
    supportsStreaming: true,
    supportsVision: false,
    isFree: true,
    category: "chat" as ModelCategory,
  },
  {
    id: "opengpt-x/teuken-7b-instruct-commercial-v0.4",
    name: "Teuken 7B Instruct Commercial",
    provider: p("opengpt-x/teuken-7b-instruct-commercial-v0.4"),
    contextLength: 32768,
    supportsStreaming: true,
    supportsVision: false,
    isFree: true,
    category: "chat" as ModelCategory,
  },
  {
    id: "qwen/qwen2-7b-instruct",
    name: "Qwen 2 7B Instruct",
    provider: p("qwen/qwen2-7b-instruct"),
    contextLength: 32768,
    supportsStreaming: true,
    supportsVision: false,
    isFree: true,
    category: "chat" as ModelCategory,
  },
  {
    id: "qwen/qwen2.5-7b-instruct",
    name: "Qwen 2.5 7B Instruct",
    provider: p("qwen/qwen2.5-7b-instruct"),
    contextLength: 32768,
    supportsStreaming: true,
    supportsVision: false,
    isFree: true,
    category: "chat" as ModelCategory,
  },
  {
    id: "qwen/qwen3.5-122b-a10b",
    name: "Qwen 3.5 122B A10B",
    provider: p("qwen/qwen3.5-122b-a10b"),
    contextLength: 131072,
    supportsStreaming: true,
    supportsVision: false,
    isFree: true,
    category: "chat" as ModelCategory,
  },
  {
    id: "qwen/qwen3.5-397b-a17b",
    name: "Qwen 3.5 397B A17B",
    provider: p("qwen/qwen3.5-397b-a17b"),
    contextLength: 131072,
    supportsStreaming: true,
    supportsVision: false,
    isFree: true,
    category: "chat" as ModelCategory,
  },
  {
    id: "rakuten/rakutenai-7b-chat",
    name: "RakutenAI 7B Chat",
    provider: p("rakuten/rakutenai-7b-chat"),
    contextLength: 32768,
    supportsStreaming: true,
    supportsVision: false,
    isFree: true,
    category: "chat" as ModelCategory,
  },
  {
    id: "rakuten/rakutenai-7b-instruct",
    name: "RakutenAI 7B Instruct",
    provider: p("rakuten/rakutenai-7b-instruct"),
    contextLength: 32768,
    supportsStreaming: true,
    supportsVision: false,
    isFree: true,
    category: "chat" as ModelCategory,
  },
  {
    id: "sarvamai/sarvam-m",
    name: "Sarvam M",
    provider: p("sarvamai/sarvam-m"),
    contextLength: 32768,
    supportsStreaming: true,
    supportsVision: false,
    isFree: true,
    category: "chat" as ModelCategory,
  },
  {
    id: "speakleash/bielik-11b-v2.3-instruct",
    name: "Bielik 11B v2.3 Instruct",
    provider: p("speakleash/bielik-11b-v2.3-instruct"),
    contextLength: 32768,
    supportsStreaming: true,
    supportsVision: false,
    isFree: true,
    category: "chat" as ModelCategory,
  },
  {
    id: "speakleash/bielik-11b-v2.6-instruct",
    name: "Bielik 11B v2.6 Instruct",
    provider: p("speakleash/bielik-11b-v2.6-instruct"),
    contextLength: 32768,
    supportsStreaming: true,
    supportsVision: false,
    isFree: true,
    category: "chat" as ModelCategory,
  },
  {
    id: "stepfun-ai/step-3.5-flash",
    name: "Step 3.5 Flash",
    provider: p("stepfun-ai/step-3.5-flash"),
    contextLength: 131072,
    supportsStreaming: true,
    supportsVision: false,
    isFree: true,
    category: "chat" as ModelCategory,
  },
  {
    id: "stockmark/stockmark-2-100b-instruct",
    name: "Stockmark 2 100B Instruct",
    provider: p("stockmark/stockmark-2-100b-instruct"),
    contextLength: 32768,
    supportsStreaming: true,
    supportsVision: false,
    isFree: true,
    category: "chat" as ModelCategory,
  },
  {
    id: "thudm/chatglm3-6b",
    name: "ChatGLM3 6B",
    provider: p("thudm/chatglm3-6b"),
    contextLength: 32768,
    supportsStreaming: true,
    supportsVision: false,
    isFree: true,
    category: "chat" as ModelCategory,
  },
  {
    id: "tiiuae/falcon3-7b-instruct",
    name: "Falcon 3 7B Instruct",
    provider: p("tiiuae/falcon3-7b-instruct"),
    contextLength: 32768,
    supportsStreaming: true,
    supportsVision: false,
    isFree: true,
    category: "chat" as ModelCategory,
  },
  {
    id: "tokyotech-llm/llama-3-swallow-70b-instruct-v0.1",
    name: "Llama 3 Swallow 70B Instruct",
    provider: p("tokyotech-llm/llama-3-swallow-70b-instruct-v0.1"),
    contextLength: 8192,
    supportsStreaming: true,
    supportsVision: false,
    isFree: true,
    category: "chat" as ModelCategory,
  },
  {
    id: "upstage/solar-10.7b-instruct",
    name: "Solar 10.7B Instruct",
    provider: p("upstage/solar-10.7b-instruct"),
    contextLength: 32768,
    supportsStreaming: true,
    supportsVision: false,
    isFree: true,
    category: "chat" as ModelCategory,
  },
  {
    id: "utter-project/eurollm-9b-instruct",
    name: "EuroLLM 9B Instruct",
    provider: p("utter-project/eurollm-9b-instruct"),
    contextLength: 8192,
    supportsStreaming: true,
    supportsVision: false,
    isFree: true,
    category: "chat" as ModelCategory,
  },
  {
    id: "writer/palmyra-creative-122b",
    name: "Palmyra Creative 122B",
    provider: p("writer/palmyra-creative-122b"),
    contextLength: 131072,
    supportsStreaming: true,
    supportsVision: false,
    isFree: true,
    category: "chat" as ModelCategory,
  },
  {
    id: "writer/palmyra-fin-70b-32k",
    name: "Palmyra Fin 70B 32K",
    provider: p("writer/palmyra-fin-70b-32k"),
    contextLength: 32768,
    supportsStreaming: true,
    supportsVision: false,
    isFree: true,
    category: "chat" as ModelCategory,
  },
  {
    id: "writer/palmyra-med-70b",
    name: "Palmyra Med 70B",
    provider: p("writer/palmyra-med-70b"),
    contextLength: 8192,
    supportsStreaming: true,
    supportsVision: false,
    isFree: true,
    category: "chat" as ModelCategory,
  },
  {
    id: "writer/palmyra-med-70b-32k",
    name: "Palmyra Med 70B 32K",
    provider: p("writer/palmyra-med-70b-32k"),
    contextLength: 32768,
    supportsStreaming: true,
    supportsVision: false,
    isFree: true,
    category: "chat" as ModelCategory,
  },
  {
    id: "yentinglin/llama-3-taiwan-70b-instruct",
    name: "Llama 3 Taiwan 70B Instruct",
    provider: p("yentinglin/llama-3-taiwan-70b-instruct"),
    contextLength: 8192,
    supportsStreaming: true,
    supportsVision: false,
    isFree: true,
    category: "chat" as ModelCategory,
  },
  {
    id: "z-ai/glm4.7",
    name: "GLM4.7",
    provider: p("z-ai/glm4.7"),
    contextLength: 131072,
    supportsStreaming: true,
    supportsVision: false,
    isFree: true,
    category: "chat" as ModelCategory,
  },
  {
    id: "z-ai/glm5",
    name: "GLM5",
    provider: p("z-ai/glm5"),
    contextLength: 131072,
    supportsStreaming: true,
    supportsVision: false,
    isFree: true,
    category: "chat" as ModelCategory,
  },
  {
    id: "zyphra/zamba2-7b-instruct",
    name: "Zamba2 7B Instruct",
    provider: p("zyphra/zamba2-7b-instruct"),
    contextLength: 32768,
    supportsStreaming: true,
    supportsVision: false,
    isFree: true,
    category: "chat" as ModelCategory,
  },
];

// ============================================================
// §2  REASONING Models (chain-of-thought)
// ============================================================

const REASONING_MODELS: NvidiaModel[] = [
  {
    id: "deepseek-ai/deepseek-r1-distill-llama-8b",
    name: "DeepSeek R1 Distill Llama 8B",
    provider: p("deepseek-ai/deepseek-r1-distill-llama-8b"),
    contextLength: 131072,
    supportsStreaming: true,
    supportsVision: false,
    isFree: true,
    category: "reasoning" as ModelCategory,
  },
  {
    id: "deepseek-ai/deepseek-r1-distill-qwen-7b",
    name: "DeepSeek R1 Distill Qwen 7B",
    provider: p("deepseek-ai/deepseek-r1-distill-qwen-7b"),
    contextLength: 131072,
    supportsStreaming: true,
    supportsVision: false,
    isFree: true,
    category: "reasoning" as ModelCategory,
  },
  {
    id: "deepseek-ai/deepseek-r1-distill-qwen-14b",
    name: "DeepSeek R1 Distill Qwen 14B",
    provider: p("deepseek-ai/deepseek-r1-distill-qwen-14b"),
    contextLength: 131072,
    supportsStreaming: true,
    supportsVision: false,
    isFree: true,
    category: "reasoning" as ModelCategory,
  },
  {
    id: "deepseek-ai/deepseek-r1-distill-qwen-32b",
    name: "DeepSeek R1 Distill Qwen 32B",
    provider: p("deepseek-ai/deepseek-r1-distill-qwen-32b"),
    contextLength: 131072,
    supportsStreaming: true,
    supportsVision: false,
    isFree: true,
    category: "reasoning" as ModelCategory,
  },
  {
    id: "microsoft/phi-4-mini-flash-reasoning",
    name: "Phi-4 Mini Flash Reasoning",
    provider: p("microsoft/phi-4-mini-flash-reasoning"),
    contextLength: 131072,
    supportsStreaming: true,
    supportsVision: false,
    isFree: true,
    category: "reasoning" as ModelCategory,
  },
  {
    id: "microsoft/phi-4-mini-instruct",
    name: "Phi-4 Mini Instruct",
    provider: p("microsoft/phi-4-mini-instruct"),
    contextLength: 131072,
    supportsStreaming: true,
    supportsVision: false,
    isFree: true,
    category: "reasoning" as ModelCategory,
  },
  {
    id: "moonshotai/kimi-k2-thinking",
    name: "Kimi K2 Thinking",
    provider: p("moonshotai/kimi-k2-thinking"),
    contextLength: 131072,
    supportsStreaming: true,
    supportsVision: false,
    isFree: true,
    category: "reasoning" as ModelCategory,
  },
  {
    id: "nvidia/cosmos-reason2-8b",
    name: "Cosmos Reason2 8B",
    provider: p("nvidia/cosmos-reason2-8b"),
    contextLength: 131072,
    supportsStreaming: true,
    supportsVision: false,
    isFree: true,
    category: "reasoning" as ModelCategory,
  },
  {
    id: "qwen/qwq-32b",
    name: "QwQ 32B",
    provider: p("qwen/qwq-32b"),
    contextLength: 131072,
    supportsStreaming: true,
    supportsVision: false,
    isFree: true,
    category: "reasoning" as ModelCategory,
  },
  {
    id: "qwen/qwen3-next-80b-a3b-thinking",
    name: "Qwen 3 Next 80B A3B Thinking",
    provider: p("qwen/qwen3-next-80b-a3b-thinking"),
    contextLength: 131072,
    supportsStreaming: true,
    supportsVision: false,
    isFree: true,
    category: "reasoning" as ModelCategory,
  },
];

// ============================================================
// §3  VISION Models (multimodal)
// ============================================================

const VISION_MODELS: NvidiaModel[] = [
  {
    id: "adept/fuyu-8b",
    name: "Fuyu 8B",
    provider: p("adept/fuyu-8b"),
    contextLength: 32768,
    supportsStreaming: true,
    supportsVision: true,
    isFree: true,
    category: "vision" as ModelCategory,
  },
  {
    id: "google/deplot",
    name: "DePlot",
    provider: p("google/deplot"),
    contextLength: 32768,
    supportsStreaming: true,
    supportsVision: true,
    isFree: true,
    category: "vision" as ModelCategory,
  },
  {
    id: "google/paligemma",
    name: "PaliGemma",
    provider: p("google/paligemma"),
    contextLength: 32768,
    supportsStreaming: true,
    supportsVision: true,
    isFree: true,
    category: "vision" as ModelCategory,
  },
  {
    id: "meta/llama-3.2-11b-vision-instruct",
    name: "Llama 3.2 11B Vision Instruct",
    provider: p("meta/llama-3.2-11b-vision-instruct"),
    contextLength: 131072,
    supportsStreaming: true,
    supportsVision: true,
    isFree: true,
    category: "vision" as ModelCategory,
  },
  {
    id: "meta/llama-3.2-90b-vision-instruct",
    name: "Llama 3.2 90B Vision Instruct",
    provider: p("meta/llama-3.2-90b-vision-instruct"),
    contextLength: 131072,
    supportsStreaming: true,
    supportsVision: true,
    isFree: true,
    category: "vision" as ModelCategory,
  },
  {
    id: "microsoft/phi-3-vision-128k-instruct",
    name: "Phi-3 Vision 128K Instruct",
    provider: p("microsoft/phi-3-vision-128k-instruct"),
    contextLength: 128000,
    supportsStreaming: true,
    supportsVision: true,
    isFree: true,
    category: "vision" as ModelCategory,
  },
  {
    id: "microsoft/phi-3.5-vision-instruct",
    name: "Phi-3.5 Vision Instruct",
    provider: p("microsoft/phi-3.5-vision-instruct"),
    contextLength: 131072,
    supportsStreaming: true,
    supportsVision: true,
    isFree: true,
    category: "vision" as ModelCategory,
  },
  {
    id: "microsoft/phi-4-multimodal-instruct",
    name: "Phi-4 Multimodal Instruct",
    provider: p("microsoft/phi-4-multimodal-instruct"),
    contextLength: 131072,
    supportsStreaming: true,
    supportsVision: true,
    isFree: true,
    category: "vision" as ModelCategory,
  },
  {
    id: "microsoft/kosmos-2",
    name: "Kosmos 2",
    provider: p("microsoft/kosmos-2"),
    contextLength: 32768,
    supportsStreaming: true,
    supportsVision: true,
    isFree: true,
    category: "vision" as ModelCategory,
  },
  {
    id: "nvidia/llama-3.1-nemotron-nano-vl-8b-v1",
    name: "Llama 3.1 Nemotron Nano VL 8B",
    provider: p("nvidia/llama-3.1-nemotron-nano-vl-8b-v1"),
    contextLength: 131072,
    supportsStreaming: true,
    supportsVision: true,
    isFree: true,
    category: "vision" as ModelCategory,
  },
  {
    id: "nvidia/nemotron-nano-12b-v2-vl",
    name: "Nemotron Nano 12B V2 VL",
    provider: p("nvidia/nemotron-nano-12b-v2-vl"),
    contextLength: 131072,
    supportsStreaming: true,
    supportsVision: true,
    isFree: true,
    category: "vision" as ModelCategory,
  },
  {
    id: "nvidia/neva-22b",
    name: "NeVA 22B",
    provider: p("nvidia/neva-22b"),
    contextLength: 131072,
    supportsStreaming: true,
    supportsVision: true,
    isFree: true,
    category: "vision" as ModelCategory,
  },
  {
    id: "nvidia/nvclip",
    name: "NVCLIP",
    provider: p("nvidia/nvclip"),
    contextLength: 32768,
    supportsStreaming: false,
    supportsVision: true,
    isFree: true,
    category: "vision" as ModelCategory,
  },
  {
    id: "nvidia/vila",
    name: "VILA",
    provider: p("nvidia/vila"),
    contextLength: 32768,
    supportsStreaming: true,
    supportsVision: true,
    isFree: true,
    category: "vision" as ModelCategory,
  },
];

// ============================================================
// §4  CODE Models
// ============================================================

const CODE_MODELS: NvidiaModel[] = [
  {
    id: "bigcode/starcoder2-7b",
    name: "StarCoder2 7B",
    provider: p("bigcode/starcoder2-7b"),
    contextLength: 16384,
    supportsStreaming: true,
    supportsVision: false,
    isFree: true,
    category: "code" as ModelCategory,
  },
  {
    id: "bigcode/starcoder2-15b",
    name: "StarCoder2 15B",
    provider: p("bigcode/starcoder2-15b"),
    contextLength: 16384,
    supportsStreaming: true,
    supportsVision: false,
    isFree: true,
    category: "code" as ModelCategory,
  },
  {
    id: "deepseek-ai/deepseek-coder-6.7b-instruct",
    name: "DeepSeek Coder 6.7B Instruct",
    provider: p("deepseek-ai/deepseek-coder-6.7b-instruct"),
    contextLength: 32768,
    supportsStreaming: true,
    supportsVision: false,
    isFree: true,
    category: "code" as ModelCategory,
  },
  {
    id: "google/codegemma-7b",
    name: "CodeGemma 7B",
    provider: p("google/codegemma-7b"),
    contextLength: 8192,
    supportsStreaming: true,
    supportsVision: false,
    isFree: true,
    category: "code" as ModelCategory,
  },
  {
    id: "google/codegemma-1.1-7b",
    name: "CodeGemma 1.1 7B",
    provider: p("google/codegemma-1.1-7b"),
    contextLength: 8192,
    supportsStreaming: true,
    supportsVision: false,
    isFree: true,
    category: "code" as ModelCategory,
  },
  {
    id: "ibm/granite-8b-code-instruct",
    name: "Granite 8B Code Instruct",
    provider: p("ibm/granite-8b-code-instruct"),
    contextLength: 32768,
    supportsStreaming: true,
    supportsVision: false,
    isFree: true,
    category: "code" as ModelCategory,
  },
  {
    id: "ibm/granite-34b-code-instruct",
    name: "Granite 34B Code Instruct",
    provider: p("ibm/granite-34b-code-instruct"),
    contextLength: 32768,
    supportsStreaming: true,
    supportsVision: false,
    isFree: true,
    category: "code" as ModelCategory,
  },
  {
    id: "meta/codellama-70b",
    name: "CodeLlama 70B",
    provider: p("meta/codellama-70b"),
    contextLength: 16384,
    supportsStreaming: true,
    supportsVision: false,
    isFree: true,
    category: "code" as ModelCategory,
  },
  {
    id: "mistralai/codestral-22b-instruct-v0.1",
    name: "Codestral 22B Instruct",
    provider: p("mistralai/codestral-22b-instruct-v0.1"),
    contextLength: 32768,
    supportsStreaming: true,
    supportsVision: false,
    isFree: true,
    category: "code" as ModelCategory,
  },
  {
    id: "mistralai/devstral-2-123b-instruct-2512",
    name: "Devstral 2 123B Instruct",
    provider: p("mistralai/devstral-2-123b-instruct-2512"),
    contextLength: 131072,
    supportsStreaming: true,
    supportsVision: false,
    isFree: true,
    category: "code" as ModelCategory,
  },
  {
    id: "mistralai/mamba-codestral-7b-v0.1",
    name: "Mamba Codestral 7B",
    provider: p("mistralai/mamba-codestral-7b-v0.1"),
    contextLength: 32768,
    supportsStreaming: true,
    supportsVision: false,
    isFree: true,
    category: "code" as ModelCategory,
  },
  {
    id: "qwen/qwen2.5-coder-7b-instruct",
    name: "Qwen 2.5 Coder 7B Instruct",
    provider: p("qwen/qwen2.5-coder-7b-instruct"),
    contextLength: 32768,
    supportsStreaming: true,
    supportsVision: false,
    isFree: true,
    category: "code" as ModelCategory,
  },
  {
    id: "qwen/qwen2.5-coder-32b-instruct",
    name: "Qwen 2.5 Coder 32B Instruct",
    provider: p("qwen/qwen2.5-coder-32b-instruct"),
    contextLength: 32768,
    supportsStreaming: true,
    supportsVision: false,
    isFree: true,
    category: "code" as ModelCategory,
  },
  {
    id: "qwen/qwen3-coder-480b-a35b-instruct",
    name: "Qwen 3 Coder 480B A35B Instruct",
    provider: p("qwen/qwen3-coder-480b-a35b-instruct"),
    contextLength: 131072,
    supportsStreaming: true,
    supportsVision: false,
    isFree: true,
    category: "code" as ModelCategory,
  },
  {
    id: "nvidia/nv-embedcode-7b-v1",
    name: "NV-EmbedCode 7B",
    provider: p("nvidia/nv-embedcode-7b-v1"),
    contextLength: 32768,
    supportsStreaming: true,
    supportsVision: false,
    isFree: true,
    category: "code" as ModelCategory,
  },
];

// ============================================================
// §5  EMBEDDING Models
// ============================================================

const EMBEDDING_MODELS: NvidiaModel[] = [
  {
    id: "baai/bge-m3",
    name: "BGE M3",
    provider: p("baai/bge-m3"),
    contextLength: 8192,
    supportsStreaming: false,
    supportsVision: false,
    isFree: true,
    category: "embedding" as ModelCategory,
  },
  {
    id: "nvidia/embed-qa-4",
    name: "NV-Embed QA 4",
    provider: p("nvidia/embed-qa-4"),
    contextLength: 512,
    supportsStreaming: false,
    supportsVision: false,
    isFree: true,
    category: "embedding" as ModelCategory,
  },
  {
    id: "nvidia/llama-3.2-nemoretriever-1b-vlm-embed-v1",
    name: "Llama 3.2 NemoRetriever 1B VLM Embed",
    provider: p("nvidia/llama-3.2-nemoretriever-1b-vlm-embed-v1"),
    contextLength: 8192,
    supportsStreaming: false,
    supportsVision: false,
    isFree: true,
    category: "embedding" as ModelCategory,
  },
  {
    id: "nvidia/llama-3.2-nemoretriever-300m-embed-v1",
    name: "Llama 3.2 NemoRetriever 300M Embed",
    provider: p("nvidia/llama-3.2-nemoretriever-300m-embed-v1"),
    contextLength: 8192,
    supportsStreaming: false,
    supportsVision: false,
    isFree: true,
    category: "embedding" as ModelCategory,
  },
  {
    id: "nvidia/llama-3.2-nv-embedqa-1b-v1",
    name: "Llama 3.2 NV-EmbedQA 1B v1",
    provider: p("nvidia/llama-3.2-nv-embedqa-1b-v1"),
    contextLength: 8192,
    supportsStreaming: false,
    supportsVision: false,
    isFree: true,
    category: "embedding" as ModelCategory,
  },
  {
    id: "nvidia/llama-3.2-nv-embedqa-1b-v2",
    name: "Llama 3.2 NV-EmbedQA 1B v2",
    provider: p("nvidia/llama-3.2-nv-embedqa-1b-v2"),
    contextLength: 8192,
    supportsStreaming: false,
    supportsVision: false,
    isFree: true,
    category: "embedding" as ModelCategory,
  },
  {
    id: "nvidia/llama-nemotron-embed-1b-v2",
    name: "Llama Nemotron Embed 1B v2",
    provider: p("nvidia/llama-nemotron-embed-1b-v2"),
    contextLength: 8192,
    supportsStreaming: false,
    supportsVision: false,
    isFree: true,
    category: "embedding" as ModelCategory,
  },
  {
    id: "nvidia/llama-nemotron-embed-vl-1b-v2",
    name: "Llama Nemotron Embed VL 1B v2",
    provider: p("nvidia/llama-nemotron-embed-vl-1b-v2"),
    contextLength: 8192,
    supportsStreaming: false,
    supportsVision: false,
    isFree: true,
    category: "embedding" as ModelCategory,
  },
  {
    id: "nvidia/nv-embed-v1",
    name: "NV-Embed v1",
    provider: p("nvidia/nv-embed-v1"),
    contextLength: 32768,
    supportsStreaming: false,
    supportsVision: false,
    isFree: true,
    category: "embedding" as ModelCategory,
  },
  {
    id: "nvidia/nv-embedqa-e5-v5",
    name: "NV-EmbedQA E5 v5",
    provider: p("nvidia/nv-embedqa-e5-v5"),
    contextLength: 32768,
    supportsStreaming: false,
    supportsVision: false,
    isFree: true,
    category: "embedding" as ModelCategory,
  },
  {
    id: "nvidia/nv-embedqa-mistral-7b-v2",
    name: "NV-EmbedQA Mistral 7B v2",
    provider: p("nvidia/nv-embedqa-mistral-7b-v2"),
    contextLength: 32768,
    supportsStreaming: false,
    supportsVision: false,
    isFree: true,
    category: "embedding" as ModelCategory,
  },
  {
    id: "snowflake/arctic-embed-l",
    name: "Arctic Embed L",
    provider: p("snowflake/arctic-embed-l"),
    contextLength: 8192,
    supportsStreaming: false,
    supportsVision: false,
    isFree: true,
    category: "embedding" as ModelCategory,
  },
];

// ============================================================
// §6  FAST Models (low-latency, lightweight)
// ============================================================

const FAST_MODELS: NvidiaModel[] = [
  {
    id: "google/gemma-2b",
    name: "Gemma 2B",
    provider: p("google/gemma-2b"),
    contextLength: 8192,
    supportsStreaming: true,
    supportsVision: false,
    isFree: true,
    category: "fast" as ModelCategory,
  },
  {
    id: "google/gemma-3-1b-it",
    name: "Gemma 3 1B IT",
    provider: p("google/gemma-3-1b-it"),
    contextLength: 131072,
    supportsStreaming: true,
    supportsVision: false,
    isFree: true,
    category: "fast" as ModelCategory,
  },
  {
    id: "google/gemma-3-4b-it",
    name: "Gemma 3 4B IT",
    provider: p("google/gemma-3-4b-it"),
    contextLength: 131072,
    supportsStreaming: true,
    supportsVision: false,
    isFree: true,
    category: "fast" as ModelCategory,
  },
  {
    id: "google/recurrentgemma-2b",
    name: "RecurrentGemma 2B",
    provider: p("google/recurrentgemma-2b"),
    contextLength: 8192,
    supportsStreaming: true,
    supportsVision: false,
    isFree: true,
    category: "fast" as ModelCategory,
  },
  {
    id: "meta/llama-3.2-1b-instruct",
    name: "Llama 3.2 1B Instruct",
    provider: p("meta/llama-3.2-1b-instruct"),
    contextLength: 131072,
    supportsStreaming: true,
    supportsVision: false,
    isFree: true,
    category: "fast" as ModelCategory,
  },
  {
    id: "nvidia/llama-3.1-nemotron-nano-4b-v1.1",
    name: "Llama 3.1 Nemotron Nano 4B v1.1",
    provider: p("nvidia/llama-3.1-nemotron-nano-4b-v1.1"),
    contextLength: 8192,
    supportsStreaming: true,
    supportsVision: false,
    isFree: true,
    category: "fast" as ModelCategory,
  },
  {
    id: "nvidia/llama-3.1-nemotron-nano-8b-v1",
    name: "Llama 3.1 Nemotron Nano 8B",
    provider: p("nvidia/llama-3.1-nemotron-nano-8b-v1"),
    contextLength: 8192,
    supportsStreaming: true,
    supportsVision: false,
    isFree: true,
    category: "fast" as ModelCategory,
  },
  {
    id: "nvidia/mistral-nemo-minitron-8b-base",
    name: "Mistral Nemo Minitron 8B Base",
    provider: p("nvidia/mistral-nemo-minitron-8b-base"),
    contextLength: 8192,
    supportsStreaming: true,
    supportsVision: false,
    isFree: true,
    category: "fast" as ModelCategory,
  },
];

// ============================================================
// §7  Full Catalog — merged and deduplicated
// ============================================================

/**
 * Complete catalog of all NVIDIA NIM API models.
 * Each model ID appears exactly once, categorized by its primary use case.
 */
export const FULL_NVIDIA_MODEL_CATALOG: NvidiaModel[] = [
  ...CHAT_MODELS,
  ...REASONING_MODELS,
  ...VISION_MODELS,
  ...CODE_MODELS,
  ...EMBEDDING_MODELS,
  ...FAST_MODELS,
];

// ============================================================
// §8  Helper Functions
// ============================================================

/**
 * Group all models by their category.
 * Returns a record mapping category name → array of models.
 */
export function getModelsByCategory(): Record<string, NvidiaModel[]> {
  const grouped: Record<string, NvidiaModel[]> = {};
  for (const model of FULL_NVIDIA_MODEL_CATALOG) {
    if (!grouped[model.category]) {
      grouped[model.category] = [];
    }
    grouped[model.category].push(model);
  }
  return grouped;
}

/**
 * Search models by a text query.
 * Matches against model ID, display name, and provider.
 * Case-insensitive partial matching.
 */
export function searchModels(query: string): NvidiaModel[] {
  const q = query.toLowerCase().trim();
  if (!q) return FULL_NVIDIA_MODEL_CATALOG;
  return FULL_NVIDIA_MODEL_CATALOG.filter(
    (m) =>
      m.id.toLowerCase().includes(q) ||
      m.name.toLowerCase().includes(q) ||
      m.provider.toLowerCase().includes(q)
  );
}

/** IDs of the 12 recommended models */
const RECOMMENDED_MODEL_IDS: string[] = [
  "meta/llama-3.3-70b-instruct",
  "google/gemma-3-27b-it",
  "qwen/qwen2.5-coder-32b-instruct",
  "moonshotai/kimi-k2-instruct",
  "deepseek-ai/deepseek-r1-distill-qwen-32b",
  "mistralai/mistral-large-3-675b-instruct-2512",
  "nvidia/llama-3.1-nemotron-ultra-253b-v1",
  "qwen/qwen3.5-397b-a17b",
  "qwen/qwen3-coder-480b-a35b-instruct",
  "meta/llama-3.2-90b-vision-instruct",
  "z-ai/glm5",
  "stepfun-ai/step-3.5-flash",
];

/**
 * Returns a curated list of ~12 top recommended models
 * spanning different categories and capabilities.
 */
export function getRecommendedModels(): NvidiaModel[] {
  const idSet = new Set(RECOMMENDED_MODEL_IDS);
  return FULL_NVIDIA_MODEL_CATALOG.filter((m) => idSet.has(m.id));
}
