import { db } from "@/lib/db";
import { readFile, writeFile, mkdir } from "fs/promises";
import { existsSync } from "fs";
import path from "path";

// ============================================================
// Constants
// ============================================================

const MEMDIR_FILE = "MEMORY.md";
const MAX_MEMDIR_SIZE = 25000; // 25KB limit
const MAX_LINES = 200;

// ============================================================
// Types
// ============================================================

export interface MemdirEntry {
  category:
    | "convention"
    | "pattern"
    | "decision"
    | "preference"
    | "error"
    | "architecture";
  content: string;
  source: string; // Which file/conversation this was learned from
  updatedAt: string;
}

// ============================================================
// Category → Section Title Mapping
// ============================================================

const CATEGORY_SECTION_TITLES: Record<MemdirEntry["category"], string> = {
  convention: "Conventions",
  pattern: "Patterns",
  decision: "Decisions",
  preference: "Preferences",
  error: "Errors & Solutions",
  architecture: "Architecture",
};

// ============================================================
// MEMORY.md Parsing
// ============================================================

/**
 * Parse MEMORY.md content into structured MemdirEntry objects.
 *
 * Expected format:
 * ```
 * # Project Memory (MEMORY.md)
 *
 * ## Conventions
 * - Use TypeScript strict mode
 * - Dark theme with emerald accents
 *
 * ## Patterns
 * - API routes use Next.js App Router
 * ```
 */
function parseMemdirMarkdown(content: string): MemdirEntry[] {
  const entries: MemdirEntry[] = [];
  const lines = content.split("\n");
  let currentCategory: MemdirEntry["category"] | null = null;
  const now = new Date().toISOString();

  // Reverse map section titles to categories
  const titleToCategory: Record<string, MemdirEntry["category"]> = {};
  for (const [cat, title] of Object.entries(CATEGORY_SECTION_TITLES)) {
    titleToCategory[title.toLowerCase()] = cat as MemdirEntry["category"];
  }

  for (const line of lines) {
    const trimmed = line.trim();

    // Match section headers: ## Category Title
    const headerMatch = trimmed.match(/^##\s+(.+)/);
    if (headerMatch) {
      const title = headerMatch[1].trim().toLowerCase();
      currentCategory = titleToCategory[title] ?? null;
      continue;
    }

    // Match list items: - content
    if (currentCategory && trimmed.startsWith("- ")) {
      const content = trimmed.slice(2).trim();
      if (content.length > 3) {
        entries.push({
          category: currentCategory,
          content,
          source: "MEMORY.md",
          updatedAt: now,
        });
      }
    }
  }

  return entries;
}

/**
 * Build MEMORY.md content from entries.
 */
function buildMemdirMarkdown(entries: MemdirEntry[]): string {
  const sections: Record<string, string[]> = {};

  for (const entry of entries) {
    const title = CATEGORY_SECTION_TITLES[entry.category];
    if (!title) continue;
    if (!sections[title]) sections[title] = [];
    sections[title].push(`- ${entry.content}`);
  }

  const header = `# Project Memory (MEMORY.md)\n\n> This file is auto-generated by CodeBot's memory system.\n> Last updated: ${new Date().toISOString()}\n`;

  const body = Object.entries(CATEGORY_SECTION_TITLES)
    .map(([cat, title]) => {
      const items = sections[title];
      if (!items || items.length === 0) return null;
      return `\n## ${title}\n${items.join("\n")}\n`;
    })
    .filter(Boolean)
    .join("\n");

  return header + body;
}

// ============================================================
// MEMORY.md File Operations
// ============================================================

/**
 * Read MEMORY.md from the given project root.
 */
async function readMemdirFile(projectRoot: string): Promise<string | null> {
  const filePath = path.join(projectRoot, MEMDIR_FILE);

  if (!existsSync(filePath)) return null;

  try {
    const content = await readFile(filePath, "utf-8");
    return content;
  } catch {
    return null;
  }
}

/**
 * Write content to MEMORY.md at the given project root.
 * Enforces MAX_LINES and MAX_MEMDIR_SIZE limits.
 */
async function writeMemdirFile(
  projectRoot: string,
  content: string
): Promise<void> {
  const dir = projectRoot;
  if (!existsSync(dir)) {
    await mkdir(dir, { recursive: true });
  }

  // Enforce line limit
  const lines = content.split("\n");
  if (lines.length > MAX_LINES) {
    // Keep header (first 3 lines) + trim from bottom
    const header = lines.slice(0, 3);
    const trimmed = lines.slice(3, MAX_LINES - 1);
    content = [...header, ...trimmed, `<!-- Trimmed: ${lines.length - MAX_LINES} lines removed -->`].join("\n");
  }

  // Enforce size limit
  if (Buffer.byteLength(content, "utf-8") > MAX_MEMDIR_SIZE) {
    // Truncate at byte boundary
    let truncated = content.slice(0, MAX_MEMDIR_SIZE - 200);
    truncated += "\n\n<!-- File truncated: exceeded 25KB limit -->\n";
    content = truncated;
  }

  const filePath = path.join(projectRoot, MEMDIR_FILE);
  await writeFile(filePath, content, "utf-8");
}

// ============================================================
// Public API — Load
// ============================================================

/**
 * Load memdir from MEMORY.md file (or DB fallback).
 * Priority:
 * 1. Read MEMORY.md from project root
 * 2. If not found, load from DB (layer: 'memdir')
 * 3. Parse into MemdirEntry objects
 * 4. Return entries sorted by updatedAt DESC
 */
export async function loadMemdir(
  projectRoot?: string
): Promise<MemdirEntry[]> {
  // Try MEMORY.md first
  if (projectRoot) {
    const fileContent = await readMemdirFile(projectRoot);
    if (fileContent) {
      const entries = parseMemdirMarkdown(fileContent);
      return entries;
    }
  }

  // Fallback to DB
  const dbEntries = await db.memory.findMany({
    where: {
      layer: "memdir",
    },
    orderBy: { updatedAt: "desc" },
    take: 100,
    select: {
      category: true,
      content: true,
      filePath: true,
      updatedAt: true,
    },
  });

  return dbEntries.map((e) => ({
    category: (e.category as MemdirEntry["category"]) || "pattern",
    content: e.content,
    source: e.filePath || "database",
    updatedAt: e.updatedAt.toISOString(),
  }));
}

// ============================================================
// Public API — Save
// ============================================================

/**
 * Save a new memdir entry (both to MEMORY.md and DB).
 * 1. Check if similar entry exists (by category + content similarity)
 * 2. If exists, update it
 * 3. If new, add to MEMORY.md under the appropriate section
 * 4. Ensure MEMORY.md doesn't exceed MAX_LINES
 * 5. Also save to DB with layer: 'memdir'
 */
export async function saveMemdirEntry(
  entry: Omit<MemdirEntry, "updatedAt">,
  projectRoot?: string
): Promise<void> {
  const now = new Date();

  // Check for existing similar entry in DB
  const existing = await db.memory.findFirst({
    where: {
      layer: "memdir",
      category: entry.category,
      content: {
        contains: entry.content.slice(0, Math.min(40, entry.content.length)),
      },
    },
  });

  if (existing) {
    // Update existing
    await db.memory.update({
      where: { id: existing.id },
      data: {
        accessCount: { increment: 1 },
        updatedAt: now,
      },
    });
  } else {
    // Create new
    await db.memory.create({
      data: {
        layer: "memdir",
        category: entry.category,
        content: entry.content,
        filePath: entry.source || null,
        tags: JSON.stringify(["memdir", entry.category]),
        importance: 6,
      },
    });
  }

  // Sync to MEMORY.md if project root is provided
  if (projectRoot) {
    // Load current entries from DB
    const allDbEntries = await db.memory.findMany({
      where: { layer: "memdir" },
      orderBy: { importance: "desc" },
      take: MAX_LINES,
      select: {
        category: true,
        content: true,
        filePath: true,
        updatedAt: true,
      },
    });

    const memdirEntries: MemdirEntry[] = allDbEntries.map((e) => ({
      category: (e.category as MemdirEntry["category"]) || "pattern",
      content: e.content,
      source: e.filePath || "database",
      updatedAt: e.updatedAt.toISOString(),
    }));

    const markdown = buildMemdirMarkdown(memdirEntries);
    await writeMemdirFile(projectRoot, markdown);
  }
}

// ============================================================
// Public API — Extract from Conversation
// ============================================================

/**
 * Extract memdir entries from recent conversation.
 * Uses heuristics to detect project-level knowledge.
 * Focused on project-level info: conventions, patterns, decisions, architecture.
 * Limits to 3 entries per call.
 */
export function extractMemdirFromConversation(
  messages: Array<{ role: string; content: string }>
): MemdirEntry[] {
  const results: MemdirEntry[] = [];
  const seenContents: string[] = [];

  const now = new Date().toISOString();

  // Process last 10 messages
  const recent = messages.slice(-10);

  for (const msg of recent) {
    if (!msg.content || msg.content.length < 15) continue;
    const text = msg.content;

    // --- Conventions: coding standards, naming patterns ---
    const conventionPatterns = [
      /(?:we |let'?s |always |make sure to )?(?:follow|use|adopt|stick with) (?:the )?(.+?) (?:naming|naming convention|style|style guide|convention|standard|format|pattern)(?:\.|,|$)/gi,
      /(?:the |our )?(?:naming|coding|style|lint|format) (?:convention|standard|rule|config|pattern) (?:is|should be|are):?\s*(.+?)(?:\.|,|$)/gi,
      /(?:snake_case|camelCase|PascalCase|kebab-case|UPPER_CASE) (?:for|used for|to name) (.+?)(?:\.|,|$)/gi,
    ];

    for (const pat of conventionPatterns) {
      pat.lastIndex = 0;
      const match = pat.exec(text);
      if (match) {
        const content = match[0].trim().replace(/[.,]$/, "");
        if (content.length > 8 && content.length < 300 && !seenContents.some((s) => content.toLowerCase().includes(s.toLowerCase()))) {
          results.push({ category: "convention", content, source: "conversation", updatedAt: now });
          seenContents.push(content);
          if (results.length >= 3) return results;
        }
      }
    }

    // --- Decisions: architectural or technology choices ---
    const decisionPatterns = [
      /(?:the )?(?:architecture|design|system|stack) (?:is|uses|should use|follows) (.+?)(?:\.|,|$)/gi,
      /(?:we |let'?s |i )?(?:decided|chose|went with|are using) (.+?) (?:for|as|because|since)(.+?)(?:\.|,|$)/gi,
    ];

    for (const pat of decisionPatterns) {
      pat.lastIndex = 0;
      const match = pat.exec(text);
      if (match) {
        const content = match[0].trim().replace(/[.,]$/, "");
        if (content.length > 8 && content.length < 300 && !seenContents.some((s) => content.toLowerCase().includes(s.toLowerCase()))) {
          results.push({ category: "decision", content, source: "conversation", updatedAt: now });
          seenContents.push(content);
          if (results.length >= 3) return results;
        }
      }
    }

    // --- Architecture: system design observations ---
    const archPatterns = [
      /(?:the )?(?:api|backend|frontend|client|server|microservice|component|module|service|handler|route) (?:is|are|should be) (?:in|located at|under|at) (.+?)(?:\.|,|$)/gi,
      /(?:the |a )?(?:data|state|config|auth|middleware|layout) (?:layer|flow|pipeline|pattern|architecture) (?:is|uses) (.+?)(?:\.|,|$)/gi,
    ];

    for (const pat of archPatterns) {
      pat.lastIndex = 0;
      const match = pat.exec(text);
      if (match) {
        const content = match[0].trim().replace(/[.,]$/, "");
        if (content.length > 8 && content.length < 300 && !seenContents.some((s) => content.toLowerCase().includes(s.toLowerCase()))) {
          results.push({ category: "architecture", content, source: "conversation", updatedAt: now });
          seenContents.push(content);
          if (results.length >= 3) return results;
        }
      }
    }

    // --- Preferences: user-level project preferences ---
    const prefPatterns = [
      /(?:i |we |the user |user )?(?:prefers?|likes?|wants?) (.+?)(?:\.|,|$)/gi,
    ];

    for (const pat of prefPatterns) {
      pat.lastIndex = 0;
      const match = pat.exec(text);
      if (match) {
        const content = match[0].trim().replace(/[.,]$/, "");
        if (content.length > 8 && content.length < 300 && !seenContents.some((s) => content.toLowerCase().includes(s.toLowerCase()))) {
          results.push({ category: "preference", content, source: "conversation", updatedAt: now });
          seenContents.push(content);
          if (results.length >= 3) return results;
        }
      }
    }

    if (results.length >= 3) return results;
  }

  return results;
}

// ============================================================
// Public API — Build Context
// ============================================================

/**
 * Build memdir context for system prompt.
 */
export function buildMemdirContext(entries: MemdirEntry[]): string {
  if (entries.length === 0) return "";

  const sections: Record<string, string[]> = {};
  for (const entry of entries) {
    const title =
      CATEGORY_SECTION_TITLES[entry.category] ??
      (entry.category.charAt(0).toUpperCase() + entry.category.slice(1) + "s");
    if (!sections[title]) sections[title] = [];
    sections[title].push(`- ${entry.content}`);
  }

  const lines = Object.entries(sections).map(
    ([title, items]) => `## ${title}\n${items.join("\n")}`
  );

  return `\n\n## Project Memory\n${lines.join("\n\n")}`;
}
